### ISSUE TITLE
How to set default download location?

### ISSUE THREAD

**Issue by crxssrazr93** [asurpbs/YT-DLP-Download-Helper#2]
Hi,

I would like an option to specify a default option in contrast to current options, which are based on %UserProfile%/downloads....

Thanks

**Comment by asurpbs** [comment]
I've added an option to set a default path. Download the script and you can see below code in 6th line.
```
set DEFAULT_PATH=%UserProfile%/downloads
```
Change `%UserProfile%/downloads` with your preferred path. I will add a feature to change these things in upcoming update. Thanks!
